### PR TITLE
Fix bug to allow custom endpoint for images

### PR DESCRIPTION
**Pull request by morrislaptop**

### CODE REVIEW

**Comment by bashaus** [comment]
Thanks for this. I think at the time of writing there was only one endpoint.

**Comment by morrislaptop** [comment]
Great :) For the custom plans they use custom endpoints (but for this scenario I just wanted to run it through runscope)

**Comment by morrislaptop** [comment]
@bashaus fancy doing another release?

**Comment by bashaus** [comment]
sure!

**Pull request merged**
